name: imodels
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - matplotlib
  - widgetsnbextension
  - ipywidgets
  - jupyter_contrib_nbextensions
  - rise
  - appmode
